version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: dokaa-back
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - dokaa-network

  frontend:
    build:
      context: ./frontend
    container_name: dokaa-front
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - dokaa-network

networks:
  dokaa-network:
    driver: bridge
